# Generated by Django 5.2.7 on 2025-12-04 14:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(db_column='IdAlumno', primary_key=True, serialize=False)),
                ('matricula', models.IntegerField(db_column='Matricula')),
                ('nombre', models.CharField(db_column='Nombre', max_length=30)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=30)),
                ('semestre', models.IntegerField(db_column='Semestre')),
                ('grupo', models.CharField(db_column='Grupo', max_length=5)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], db_column='Estado', max_length=15)),
            ],
            options={
                'db_table': 'alumnos',
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(db_column='IdAutor', primary_key=True, serialize=False)),
                ('nacionalidad', models.CharField(db_column='Nacionalidad', max_length=30)),
                ('nombre', models.CharField(db_column='Nombre', max_length=30)),
            ],
            options={
                'db_table': 'autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='IdCategoria', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(db_column='NombreCategoria', max_length=30)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id_devolucion', models.AutoField(db_column='IdDevolucion', primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateField(db_column='FechaEntrega')),
                ('observaciones', models.CharField(blank=True, db_column='Observaciones', max_length=50, null=True)),
            ],
            options={
                'db_table': 'devoluciones',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='IdRol', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_column='NombreRol', max_length=20)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(db_column='IdLibro', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='Titulo', max_length=30)),
                ('editorial', models.CharField(db_column='Editorial', max_length=30)),
                ('anio', models.IntegerField(db_column='Anio')),
                ('cantidad_disponible', models.IntegerField(db_column='CantidadDisponible')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='libros/')),
                ('categoria', models.ForeignKey(db_column='IdCategoria', on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.categoria')),
            ],
            options={
                'db_table': 'libros',
            },
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id_ejemplar', models.AutoField(db_column='IdEjemplar', primary_key=True, serialize=False)),
                ('num_ejemplar', models.IntegerField(db_column='NumEjemplar')),
                ('estado_ejemplar', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('dañado', 'Dañado')], db_column='EstadoEjemplar', max_length=20)),
                ('libro', models.ForeignKey(db_column='IdLibro', on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.libro')),
            ],
            options={
                'db_table': 'ejemplares',
            },
        ),
        migrations.CreateModel(
            name='LibroAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.ForeignKey(db_column='IdAutor', on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.autor')),
                ('libro', models.ForeignKey(db_column='IdLibro', on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.libro')),
            ],
            options={
                'db_table': 'libro_autor',
                'unique_together': {('libro', 'autor')},
            },
        ),
        migrations.AddField(
            model_name='libro',
            name='autores',
            field=models.ManyToManyField(related_name='libros', through='biblioteca_app.LibroAutor', to='biblioteca_app.autor'),
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id_multa', models.AutoField(db_column='IdMulta', primary_key=True, serialize=False)),
                ('monto', models.DecimalField(db_column='Monto', decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(blank=True, db_column='Motivo', max_length=30, null=True)),
                ('devolucion', models.ForeignKey(db_column='IdDevolucion', on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.devolucion')),
            ],
            options={
                'db_table': 'multas',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(db_column='IdPrestamo', primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField(db_column='FechaPrestamo')),
                ('fecha_vencimiento', models.DateField(db_column='FechaVencimiento')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('devuelto', 'Devuelto'), ('retrasado', 'Retrasado')], db_column='Estado', max_length=15)),
                ('alumno', models.ForeignKey(db_column='IdAlumno', on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.alumno')),
                ('ejemplar', models.ForeignKey(db_column='IdEjemplar', on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.ejemplar')),
            ],
            options={
                'db_table': 'prestamos',
            },
        ),
        migrations.AddField(
            model_name='devolucion',
            name='prestamo',
            field=models.ForeignKey(db_column='IdPrestamo', on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.prestamo'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('alumno', models.ForeignKey(blank=True, db_column='IdAlumno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca_app.alumno')),
                ('rol', models.ForeignKey(db_column='IdRol', on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.rol')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
