# Generated by Django 5.2.7 on 2025-12-04 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, db_column='IdRol', null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.rol'),
        ),
    ]
