# Generated by Django 5.2.7 on 2025-12-04 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0004_alter_libro_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multa',
            name='devolucion',
        ),
        migrations.AddField(
            model_name='multa',
            name='prestamo',
            field=models.ForeignKey(db_column='IdPrestamo', default=1, on_delete=django.db.models.deletion.CASCADE, to='biblioteca_app.prestamo'),
            preserve_default=False,
        ),
    ]
