# Generated by Django 5.2.7 on 2025-12-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0005_remove_multa_devolucion_multa_prestamo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multa',
            name='monto',
            field=models.DecimalField(db_column='Monto', decimal_places=2, max_digits=10, null=True),
        ),
    ]
