# Generated by Django 5.2.7 on 2025-12-04 22:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0006_alter_multa_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='multa',
            name='fecha',
            field=models.DateField(auto_now_add=True, db_column='Fecha', default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
