# Generated by Django 5.2.7 on 2025-12-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_app', '0007_multa_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='sinopsis',
            field=models.TextField(blank=True, db_column='Sinopsis', null=True),
        ),
    ]
